services:
  py:
    build:
      context: hal9003
      dockerfile: ./Dockerfile
    image: "${IMAGE_PREFIX-}bot-python:${IMAGE_TAG-latest}"
    volumes:
      - ./hal9003:/bot
    environment:
      DEBUG: ${DEBUG:-true}
      SERVER_HOST: ${SERVER_HOST:-host.docker.internal:8000}
      SERVER_USE_SSL: ${SERVER_USE_SSL:-false}
      BOT_USERNAME: ${BOT_USERNAME:-bot}
      BOT_PASSWORD: ${BOT_PASSWORD:-password}
      BOT_ONLY: ${BOT_ONLY:-true}
      WEBSOCKET_PORT: ${WEBSOCKET_PORT:-8000}
      USE_REDIS: ${USE_REDIS:-true}
      REDIS_URL: ${REDIS_URL:-redis://host.docker.internal:6380/0}
      AI_CONNECT_STRING: ${AI_CONNECT_STRING:-@@ai@}
      INFINITE_RETRY: ${INFINITE_RETRY:-true}
      DEBUG_CHAT_TITLE: ${DEBUG_CHAT_TITLE:-hal9003-debug}
      DEEPINFRA_API_KEY: ${DEEPINFRA_API_KEY:-}
      MODEL_BACKEND: ${MODEL_BACKEND:-openai}
      DEFAULT_MODEL: ${DEFAULT_MODEL:-gpt-3.5-turbo}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    ports:
      - "3334:3334"
  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
